author: B1acksheep
description: BookExploitQuickFix
main: de.b1acksheep.bookexploitquickfix.BookExploitQuickFixPluign
name: BookExploitQuickFix
version: "${project.version}"
startup: postworld
database: true